version: '3.8'
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: shop_inventory
    ports:
      - "5433:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST: db
      POSTGRES_PORT: 5433
      POSTGRES_DB: shop_inventory
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
volumes:
  pgdata: 